apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeton-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: freeton-node
  template:
    metadata:
      labels:
        app: freeton-node
    spec:
      containers:
        - name: ton-node
          image: freetondreamteam/ton-node:0.1
          ports:
            - name: freeton-console
              containerPort: 43678
            - name: freeton-lite
              containerPort: 43679
          resources:
            limits:
              memory: 3Gi
              cpu: 1
            requests:
              cpu: 1
              memory: 3Gi
          command: ['/usr/bin/sleep']
          args: ['infinity']
      volumes:
        - name: freeton-data
