apiVersion: v1
kind: Service
metadata:
  name: freeton-node-1-external
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs: [134.209.250.33]
  ports:
    - port: 30310
      protocol: UDP
      targetPort: 30310
  selector:
    app: freeton-node-1
---
apiVersion: v1
kind: Service
metadata:
  name: freeton-node-1-internal
spec:
  type: LoadBalancer
  ports:
    - name: freeton-console
      port: 3030
      protocol: TCP
      targetPort: 3030
    - name: freeton-lite
      port: 3031
      protocol: TCP
      targetPort: 3031
  selector:
    app: freeton-node-1
