apiVersion: v1
kind: PersistentVolume
metadata:
  name: freeton-node-1-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/freeton-node-1-pv-volume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeton-node-1-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
