apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeton-node-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freeton-node-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: freeton-node-test
    spec:
      nodeName: ton-k8s-1
      containers:
        - image: freetondreamteam/ton-node:0.3.1
          name: freeton-node
          securityContext:
            runAsUser: 0
          ports:
              - name: zabbix-agent
                containerPort: 10050
          command:
            - bash
            - '-c'
            - |
              /usr/sbin/zabbix_agent2 &
              dnf install logrotate -y
              rpm -i http://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-agent2-5.0.1-1.el8.x86_64.rpm
              /bin/sleep infinity
