{
 "title": "Ton Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TON: IP allocation was seeded by different peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"IP allocation was seeded by different peers\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "TON: Multiple connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"connection shutting down due to error: Multiple connections\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "TON: Connection reset by peer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"connection shutting down due to error:\" AND \"connection reset by peer\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "TON: Operation not permitted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"Operation not permitted\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "TON: Slow apply block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"SLOW: [name:applyblock]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Initiator hostname",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "node-1",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "\"Initiator hostname:\" AND \"freeton-node-1-internal\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "node-2",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "\"Initiator hostname:\" AND \"freeton-node-2-internal\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Confirmator hostname",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "node-1",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "\"Confirmator hostname\" AND \"freeton-node-1-internal\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "node-2",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "\"Confirmator hostname\" AND \"freeton-node-2-internal\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Submit election transaction",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pass",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"submitElectionTransaction\" AND \"PASS\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "fail",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"submitElectionTransaction\" AND \"FAIL\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Confirm election transaction",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pass",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"confirmElectionTransaction\" AND \"PASS\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "fail",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"confirmElectionTransaction\" AND \"FAIL\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Submit recover transaction",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pass",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"submitRecoverTransaction\" AND \"PASS\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "fail",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"submitRecoverTransaction\" AND \"FAIL\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Ton logs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Account updates between the old and the new state",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "AccountBlocks, and all transactions of all accounts",
     "timeField": "@timestamp"
    },
    {
     "alias": "Running automated validity checks for block candidate",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "running automated validity checks for block candidate",
     "timeField": "@timestamp"
    },
    {
     "alias": "Checking header of the new shardchain state",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "checking header of the new shardchain state",
     "timeField": "@timestamp"
    },
    {
     "alias": "Checking all transactions",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "checking all transactions",
     "timeField": "@timestamp"
    },
    {
     "alias": "ProcessedInfo claims to have processed all inbound messages up to",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "ProcessedInfo claims to have processed all inbound messages up to",
     "timeField": "@timestamp"
    },
    {
     "alias": "Scanning new outbound queue and checking delivery status of all messages",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "scanning new outbound queue and checking delivery status of all messages",
     "timeField": "@timestamp"
    },
    {
     "alias": "checking ProcessedInfo",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "checking ProcessedInfo",
     "timeField": "@timestamp"
    },
    {
     "alias": "checking outbound messages listed in OutMsgDescr",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "checking outbound messages listed in OutMsgDescr",
     "timeField": "@timestamp"
    },
    {
     "alias": "checking inbound messages listed in InMsgDescr",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "checking inbound messages listed in InMsgDescr",
     "timeField": "@timestamp"
    },
    {
     "alias": "Validate query for XXX started",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "validate query for",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}