apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      nodeName: ton-k8s-0
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-mysql:centos-5.0-latest
          ports: [{containerPort: 8080}]
          env:
            - name: DB_SERVER_HOST
              value: 'mysql'
            - name: MYSQL_USER
              value: 'zabbix'
            - name: MYSQL_PASSWORD
              value: 'zabbix'
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs: [161.35.202.55]
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: zabbix-web
