apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: elk
  labels:
    app: nginx
data:
  default.conf: |-
    upstream kibana {
        server kibana.elk.svc.cluster.local:5601;
        keepalive 15;
    }

    server {
      listen 8888;

      location / {
          proxy_pass http://kibana;
          proxy_redirect off;
          proxy_buffering off;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: elk
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx
          configMap:
            name: nginx
      containers:
        - name: nginx
          image: nginx:1.17
          ports:
            - containerPort: 8888
              protocol: TCP
          volumeMounts:
            - name: nginx
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: elk
  labels:
    app: nginx
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs:
    - 134.209.250.33
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: nginx
